const $=s=>document.querySelector(s);const cfg=window.APP_CONFIG||{};const catalog=window.QUIZ_CATALOG||[];let sb=null,allRows=[];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function ready(){const k=String(cfg.SUPABASE_ANON_KEY||'');return !!(cfg.SUPABASE_URL&&k&&!/DAN_|PASTE|YOUR_/i.test(k)&&(k.startsWith('sb_publishable_')||k.startsWith('eyJ'))&&window.supabase)}
function client(){if(!ready())throw new Error('Publishable key trong config.js chưa hợp lệ.');if(!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);return sb}
function fmtDate(v){return v?new Date(v).toLocaleString('vi-VN'):'—'}function fmtDur(s){s=Number(s||0);if(s<60)return s+' giây';return Math.floor(s/60)+'p '+(s%60)+'s'}
async function login(){try{const c=client();$('#msg').textContent='';const r=await c.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error)throw r.error;await showDash()}catch(e){$('#msg').textContent=e.message||e}}
async function showDash(){try{const c=client();const sess=await c.auth.getSession();if(!sess.data.session)return;$('#loginBox').classList.add('hidden');$('#dash').classList.remove('hidden');const r=await c.rpc('admin_attempts');if(r.error)throw r.error;allRows=r.data||[];populateFilters();render()}catch(e){$('#msg').textContent=e.message||e;$('#loginBox').classList.remove('hidden');$('#dash').classList.add('hidden')}}
function populateFilters(){const sel=$('#chapterFilter');if(sel.options.length===1)catalog.forEach(c=>sel.insertAdjacentHTML('beforeend',`<option value="${esc(c.title)}">${esc(c.title)}</option>`));}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase(),ch=$('#chapterFilter').value,flag=$('#flagFilter').value;return allRows.filter(r=>(!q||`${r.full_name} ${r.class_name}`.toLowerCase().includes(q))&&(!ch||r.chapter_title===ch)&&(!flag||(flag==='flagged'?r.flagged:!r.flagged)))}
function render(){const rows=filtered();$('#adminStats').innerHTML=`<div><strong>${rows.length}</strong><span>Lượt đã nộp</span></div><div><strong>${new Set(rows.map(r=>`${r.full_name}|${r.class_name}`)).size}</strong><span>Người học</span></div><div><strong>${rows.length?(rows.reduce((a,b)=>a+Number(b.percent||0),0)/rows.length).toFixed(1):'0'}%</strong><span>Điểm trung bình</span></div><div><strong>${rows.filter(r=>r.flagged).length}</strong><span>Bài có ghi nhận</span></div>`;$('#rows').innerHTML=rows.map(r=>`<tr><td><b>${esc(r.full_name)}</b></td><td>${esc(r.class_name)}</td><td>${esc(r.chapter_title)}</td><td>${r.attempt_number}</td><td><b>${r.score}/${r.total_questions}</b></td><td>${Number(r.percent).toFixed(1)}%</td><td>${fmtDur(r.duration_seconds)}</td><td>${r.flagged?'<span class="flag bad">Có ghi nhận</span>':'<span class="flag ok">Bình thường</span>'}</td><td>${fmtDate(r.submitted_at)}</td><td><button class="mini-btn" data-id="${r.attempt_id}">Chi tiết</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty-cell">Chưa có dữ liệu phù hợp.</td></tr>';document.querySelectorAll('.mini-btn').forEach(b=>b.onclick=()=>openDetail(b.dataset.id));}
async function openDetail(id){try{const r=await client().rpc('admin_attempt_detail',{p_attempt_id:id});if(r.error)throw r.error;let d=r.data;if(typeof d==='string')d=JSON.parse(d);$('#detailTitle').textContent=`${d.full_name} · ${d.class_name}`;const rev=d.review||[],ev=d.monitor_log||[];$('#detailBody').innerHTML=`<div class="detail-summary"><div><span>Chương</span><b>${esc(d.chapter_title)}</b></div><div><span>Lượt</span><b>${d.attempt_number}</b></div><div><span>Điểm</span><b>${d.score}/${d.total_questions} · ${Number(d.percent).toFixed(1)}%</b></div><div><span>Thời gian</span><b>${fmtDur(d.duration_seconds)}</b></div></div><h3>Đáp án đã chọn</h3><div class="detail-answer-grid">${rev.map(x=>`<div class="detail-answer ${x.is_correct?'ok':'bad'}"><b>C${x.question_no}</b><span>${esc(x.selected_option)} → ${esc(x.correct_option)}</span></div>`).join('')}</div><h3>Nhật ký giám sát</h3>${ev.length?`<div class="event-log">${ev.map(e=>`<div><time>${fmtDate(e.occurred_at)}</time><b>${esc(e.event_type)}</b><span>${esc(JSON.stringify(e.event_detail||{}))}</span></div>`).join('')}</div>`:'<p class="muted">Không có sự kiện giám sát.</p>'}`;$('#detailModal').classList.remove('hidden')}catch(e){alert(e.message||e)}}
function csv(){const rows=filtered(),cols=['Họ tên','Lớp','Chương','Lượt','Điểm','Tổng','Phần trăm','Thời gian giây','Có ghi nhận','Nộp lúc'];const lines=[cols,...rows.map(r=>[r.full_name,r.class_name,r.chapter_title,r.attempt_number,r.score,r.total_questions,r.percent,r.duration_seconds,r.flagged?'Có':'Không',r.submitted_at])].map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ket-qua-trac-nghiem.csv';a.click();URL.revokeObjectURL(a.href)}
$('#login').onclick=login;$('#logout').onclick=async()=>{await client().auth.signOut();location.reload()};$('#refresh').onclick=showDash;$('#exportCsv').onclick=csv;['searchInput','chapterFilter','flagFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'?'input':'change',render));$('#closeModal').onclick=()=>$('#detailModal').classList.add('hidden');document.querySelector('[data-close="1"]').onclick=()=>$('#detailModal').classList.add('hidden');
try{if(ready())client().auth.getSession().then(x=>{if(x.data.session)showDash()})}catch(e){}
