const $=s=>document.querySelector(s);
const cfg=window.APP_CONFIG||{};
const catalog=window.QUIZ_CATALOG||[];
const chapterSlug=new URLSearchParams(location.search).get('chapter')||'chuong-1';
const meta=catalog.find(x=>x.slug===chapterSlug)||catalog[0];
let sb=null,attempt=null,questions=[],answers={},heartbeatTimer=null,awayStarted=null,monitoringArmed=false,fullscreenStarted=false;
const sessionToken=(crypto.randomUUID?crypto.randomUUID():'s-'+Date.now()+'-'+Math.random().toString(36).slice(2));
const letters=['A','B','C','D'];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function configReady(){const k=String(cfg.SUPABASE_ANON_KEY||'');return !!(cfg.SUPABASE_URL&&k&&!/DAN_|PASTE|YOUR_/i.test(k)&&(k.startsWith('sb_publishable_')||k.startsWith('eyJ'))&&window.supabase)}
function initClient(){if(configReady()&&!sb)sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true}});return sb}
function browserId(){let id=localStorage.getItem('quiz_browser_id');if(!id){id=crypto.randomUUID?crypto.randomUUID():'b-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem('quiz_browser_id',id)}return id}
function humanError(e){const m=String(e?.message||e||'');if(/Invalid API key/i.test(m))return 'Publishable key trong config.js chưa đúng. Hãy dán đúng key bắt đầu bằng sb_publishable_...';if(/Failed to fetch|NetworkError/i.test(m))return 'Không kết nối được Supabase. Kiểm tra Internet và cấu hình project.';return m||'Có lỗi xảy ra.'}
function renderRich(text=''){const lines=String(text).split(/\n/);let h='',inList=false;for(const raw of lines){const line=raw.trimEnd();if(/^\s*-\s+/.test(line)){if(!inList){h+='<ul>';inList=true}h+=`<li>${esc(line.replace(/^\s*-\s+/,''))}</li>`}else{if(inList){h+='</ul>';inList=false}if(line.trim())h+=`<p>${esc(line)}</p>`}}if(inList)h+='</ul>';return h}
function initMeta(){if(!meta){$('#introTitle').textContent='Không tìm thấy chương';$('#startBtn').disabled=true;return}document.title=meta.title+' · Làm bài';$('#introTitle').textContent=meta.title;$('#quizTitle').textContent=meta.title;$('#chapterNumberPill').textContent=`Chương ${meta.number} · 40 câu`;}
initMeta();
async function start(){const fullName=$('#fullName').value.trim(),className=$('#className').value.trim();$('#startMsg').textContent='';if(!fullName||!className){$('#startMsg').textContent='Vui lòng nhập đầy đủ Họ và tên và Lớp.';return}if(!configReady()){ $('#startMsg').innerHTML='Chưa kết nối được Supabase vì <b>Publishable key</b> trong <code>config.js</code> chưa hợp lệ.';return}localStorage.setItem('last_student_name',fullName);localStorage.setItem('last_student_class',className);$('#startBtn').disabled=true;$('#startBtn').textContent='Đang mở bài...';try{initClient();const r=await sb.rpc('start_or_resume_attempt',{p_chapter_slug:chapterSlug,p_full_name:fullName,p_class_name:className,p_browser_id:browserId(),p_session_token:sessionToken});if(r.error)throw r.error;const row=Array.isArray(r.data)?r.data[0]:r.data;const qr=await sb.rpc('get_quiz_questions',{p_chapter_slug:chapterSlug});if(qr.error)throw qr.error;const ar=await sb.rpc('get_saved_answers',{p_attempt_id:row.attempt_id});if(ar.error)throw ar.error;attempt={id:row.attempt_id,number:row.attempt_number,monitoring:row.monitoring_required,fullName,className};questions=(qr.data||[]).map(x=>({id:x.question_id,no:x.question_no,section:x.section_label,text:x.question_text,options:{A:x.option_a,B:x.option_b,C:x.option_c,D:x.option_d}}));answers=Object.fromEntries((ar.data||[]).map(x=>[x.question_id,x.selected_option]));$('#identityPanel').classList.add('hidden');$('#quizMain').classList.add('active');$('#studentLine').textContent=`${fullName} · Lớp ${className}`;$('#attemptText').textContent=`Lượt ${attempt.number}${attempt.monitoring?' · Giám sát':''}`;$('#saveBadge').textContent='Tự động lưu';renderQuestions();renderNav();updateProgress();if(attempt.monitoring)await enableMonitoring();window.scrollTo({top:0,behavior:'smooth'});}catch(e){$('#startMsg').textContent='Không mở được bài: '+humanError(e)}finally{$('#startBtn').disabled=false;$('#startBtn').textContent='Bắt đầu / Tiếp tục bài →'}}
function renderQuestions(){let lastSection='';let html='';for(const q of questions){if(q.section&&q.section!==lastSection){lastSection=q.section;html+=`<div class="section-divider"><span>${esc(q.section)}</span></div>`}html+=`<article class="question ${answers[q.id]?'done':''}" id="q-${q.no}"><div class="q-top"><span class="q-no">Câu ${q.no}</span><span class="q-status">${answers[q.id]?'Đã chọn':'Chưa chọn'}</span></div><div class="q-text rich">${renderRich(q.text)}</div><div class="options">${letters.map(k=>`<label class="option"><input type="radio" name="q_${esc(q.id)}" value="${k}" ${answers[q.id]===k?'checked':''}><span class="option-letter">${k}</span><span class="option-text">${esc(q.options[k])}</span></label>`).join('')}</div></article>`}$('#questions').innerHTML=html;document.querySelectorAll('.question input').forEach(el=>el.addEventListener('change',onAnswer));}
async function onAnswer(e){const id=e.target.name.slice(2);answers[id]=e.target.value;const card=e.target.closest('.question');card.classList.add('done');card.querySelector('.q-status').textContent='Đã chọn';updateProgress();markNav();$('#saveText').textContent='Đang lưu...';try{const r=await sb.rpc('save_answer',{p_attempt_id:attempt.id,p_question_id:id,p_selected_option:e.target.value});if(r.error)throw r.error;$('#saveText').textContent='Đã lưu';$('#saveBadge').textContent='Đã lưu'}catch(err){$('#saveText').textContent='Lỗi lưu';$('#submitNotice').textContent='Một đáp án chưa lưu được: '+humanError(err)}}
function renderNav(){$('#qNav').innerHTML=questions.map(q=>`<button data-no="${q.no}" class="${answers[q.id]?'done':''}">${q.no}</button>`).join('');document.querySelectorAll('#qNav button').forEach(b=>b.onclick=()=>document.querySelector('#q-'+b.dataset.no).scrollIntoView({behavior:'smooth',block:'start'}));}
function markNav(){questions.forEach(q=>{const b=document.querySelector(`#qNav button[data-no="${q.no}"]`);if(b)b.classList.toggle('done',!!answers[q.id])})}
function updateProgress(){const n=Object.keys(answers).length,total=questions.length||40,remaining=total-n;$('#progressText').textContent=`${n}/${total}`;$('#remainingText').textContent=remaining?`Còn ${remaining} câu`:'Đã trả lời đủ';$('#progressBar').style.width=`${Math.round(n/total*100)}%`;$('#submitBtn').disabled=remaining!==0;}
async function logEvent(type,detail={}){if(!attempt?.monitoring||!sb)return;try{await sb.rpc('log_monitor_event',{p_attempt_id:attempt.id,p_session_token:sessionToken,p_event_type:type,p_event_detail:detail})}catch(e){}}
async function enableMonitoring(){if(monitoringArmed)return;monitoringArmed=true;$('#monitorBadge').classList.remove('hidden');const leaveKey='quiz_leave_'+attempt.id;const prior=localStorage.getItem(leaveKey);if(prior){await logEvent('page_leave_resume',{left_at:prior});localStorage.removeItem(leaveKey)}try{if(document.documentElement.requestFullscreen&&!document.fullscreenElement){await document.documentElement.requestFullscreen();fullscreenStarted=!!document.fullscreenElement}}catch(e){}
document.addEventListener('visibilitychange',()=>{if(document.hidden){awayStarted=Date.now();logEvent('tab_hidden')}else{const d=awayStarted?Math.max(0,Math.round((Date.now()-awayStarted)/1000)):0;awayStarted=null;logEvent('tab_visible',{away_seconds:d})}});window.addEventListener('blur',()=>logEvent('window_blur'));document.addEventListener('fullscreenchange',()=>{if(fullscreenStarted&&!document.fullscreenElement)logEvent('fullscreen_exit')});const markLeave=()=>{try{localStorage.setItem(leaveKey,new Date().toISOString())}catch(e){}};window.addEventListener('pagehide',markLeave);window.addEventListener('beforeunload',markLeave);heartbeatTimer=setInterval(()=>sb.rpc('touch_attempt_session',{p_attempt_id:attempt.id,p_session_token:sessionToken}).catch(()=>{}),8000);await sb.rpc('touch_attempt_session',{p_attempt_id:attempt.id,p_session_token:sessionToken}).catch(()=>{});}
function memeFor(p){if(p===100)return['assets/meme-perfect.svg','Xuất sắc tuyệt đối!','40/40 — không để rơi một điểm nào.'];if(p>=90)return['assets/meme-great.svg','Đỉnh quá rồi!','Kiến thức đang vào form rất đẹp.'];if(p>=75)return['assets/meme-great.svg','Ổn áp!','Nền tảng chắc, xem lại vài câu sai là rất đẹp.'];if(p>=50)return['assets/meme-mid.svg','Suýt đẹp rồi!','Đọc kỹ phần giải thích bên dưới và thử lại nhé.'];return['assets/meme-retry.svg','Chương này đang gọi tên...','Ôn lại từng mục rồi quay lại phục thù!']}
async function submit(){const missing=questions.filter(q=>!answers[q.id]).map(q=>q.no);$('#submitNotice').textContent='';if(missing.length){$('#submitNotice').textContent=`Bạn còn ${missing.length} câu chưa trả lời: ${missing.join(', ')}.`;document.querySelector('#q-'+missing[0])?.scrollIntoView({behavior:'smooth'});return}if(!confirm('Bạn đã trả lời đủ 40 câu. Nộp bài ngay?'))return;$('#submitBtn').disabled=true;$('#submitBtn').textContent='Đang chấm...';try{const r=await sb.rpc('submit_attempt',{p_attempt_id:attempt.id,p_session_token:sessionToken});if(r.error)throw r.error;let result=Array.isArray(r.data)?r.data[0]:r.data;for(const k of ['review','monitor_summary','monitor_log'])if(typeof result[k]==='string')try{result[k]=JSON.parse(result[k])}catch(e){};if(heartbeatTimer)clearInterval(heartbeatTimer);localStorage.removeItem('quiz_leave_'+attempt.id);showResult(result)}catch(e){$('#submitNotice').textContent='Chưa nộp được bài: '+humanError(e);$('#submitBtn').disabled=false;$('#submitBtn').textContent='Nộp bài'}}
function showResult(r){$('#quizMain').classList.remove('active');$('#result').classList.add('active');$('#scoreBig').textContent=`${r.score}/${r.total}`;$('#scoreMeta').textContent=`${Number(r.percent).toFixed(Number(r.percent)%1?1:0)}% · ${r.correct_count} câu đúng · ${r.wrong_count} câu sai · Lượt ${r.attempt_number}`;const [img,title,msg]=memeFor(Number(r.percent));$('#meme').innerHTML=`<img src="${img}" alt="Meme kết quả"><div><strong>${esc(title)}</strong><p>${esc(msg)}</p></div>`;renderMonitor(r);renderReview(r.review||[]);window.scrollTo({top:0,behavior:'smooth'});}
function renderMonitor(r){const box=$('#monitorReport');if(!r.monitoring_required){box.innerHTML='';return}const s=r.monitor_summary||{},events=r.monitor_log||[];const count=(s.tab_hidden||0)+(s.window_blur||0)+(s.fullscreen_exit||0)+(s.page_leave_resume||0)+(s.concurrent_session||0);box.innerHTML=`<div class="monitor-report"><div class="monitor-title"><span>Nhật ký giám sát lượt ${r.attempt_number}</span><b>${count?`${count} ghi nhận`:'Không có ghi nhận đáng chú ý'}</b></div><div class="monitor-stats"><span>Chuyển/ẩn tab <b>${s.tab_hidden||0}</b></span><span>Mất focus <b>${s.window_blur||0}</b></span><span>Thoát toàn màn hình <b>${s.fullscreen_exit||0}</b></span><span>Rời rồi quay lại <b>${s.page_leave_resume||0}</b></span><span>Phiên song song <b>${s.concurrent_session||0}</b></span><span>Thời gian ngoài tab <b>${s.total_away_seconds||0}s</b></span></div>${events.length?`<details><summary>Xem chi tiết sự kiện</summary><div class="event-log">${events.map(e=>`<div><time>${new Date(e.occurred_at).toLocaleString('vi-VN')}</time><b>${esc(e.event_type)}</b><span>${esc(JSON.stringify(e.event_detail||{}))}</span></div>`).join('')}</div></details>`:''}</div>`;}
function renderReview(items){let last='';let h='<div class="review-head"><div><div class="eyebrow small">XEM LẠI BÀI</div><h2>Đáp án & giải thích đầy đủ</h2><p>Toàn bộ câu hỏi được giữ nguyên nội dung. Đáp án đúng được đánh dấu màu xanh.</p></div></div>';for(const it of items){if(it.section_label&&it.section_label!==last){last=it.section_label;h+=`<div class="section-divider review-divider"><span>${esc(it.section_label)}</span></div>`}const opts=it.options||{};h+=`<article class="review-item ${it.is_correct?'ok':'bad'}"><div class="review-top"><span class="q-no">Câu ${it.question_no}</span><span class="result-chip ${it.is_correct?'ok':'bad'}">${it.is_correct?'Đúng ✓':'Sai ✕'}</span></div><div class="q-text rich">${renderRich(it.question_text)}</div><div class="review-options">${letters.map(k=>{const cls=[k===it.correct_option?'correct':'',k===it.selected_option?'selected':''].filter(Boolean).join(' ');return `<div class="review-option ${cls}"><span class="option-letter">${k}</span><span>${esc(opts[k]||'')}</span>${k===it.correct_option?'<b>Đáp án đúng</b>':''}${k===it.selected_option&&k!==it.correct_option?'<b class="your-choice">Bạn chọn</b>':''}</div>`}).join('')}</div><div class="answer-summary"><span>Bạn chọn: <b>${esc(it.selected_option)}</b></span><span>Đáp án đúng: <b>${esc(it.correct_option)}</b></span></div><div class="exp"><strong>Giải thích</strong><div class="rich">${renderRich(it.explanation||'')}</div></div>${it.topic?`<div class="topic"><strong>Nội dung thuộc</strong><div class="rich">${renderRich(it.topic)}</div></div>`:''}</article>`}$('#review').innerHTML=h;}
$('#startBtn').addEventListener('click',start);$('#submitBtn').addEventListener('click',submit);$('#retryBtn').addEventListener('click',()=>{location.href=`quiz.html?chapter=${encodeURIComponent(chapterSlug)}`});
